[package]
name = "neo-nickbot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.anyhow]
version = "1.0.40"

[dependencies.serenity]
version = "0.10.7"
features = ["gateway", "rustls_backend", "model", "unstable_discord_api"]

[dependencies.tokio]
version = "1.6.0"
features = ["full"]
